"""Initial migration

Revision ID: 7a1865bc4c0c
Revises: 
Create Date: 2025-12-22 19:51:47.748343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a1865bc4c0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    op.drop_table('clinical_versions')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_orders_episode'))

    op.drop_table('orders')
    op.drop_table('access_logs')
    op.drop_table('results')
    op.drop_table('order_items')
    with op.batch_alter_table('prestations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('code'))

    op.drop_table('prestations')
    op.drop_table('plans')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('key_name'))

    op.drop_table('system_settings')
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('permissions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_payments_invoice'))

    op.drop_table('payments')
    op.drop_table('affiliations')
    op.drop_table('plan_tariffs')
    op.drop_table('payers')
    op.drop_table('notification_logs')
    with op.batch_alter_table('agenda_blocks', schema=None) as batch_op:
        batch_op.alter_column('state',
               existing_type=mysql.ENUM('AVAILABLE', 'BLOCKED', 'OCCUPIED'),
               nullable=False,
               existing_server_default=sa.text("'AVAILABLE'"))
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('CONSULTATION', 'PROCEDURE', 'INTERCONSULTATION'),
               nullable=False,
               existing_server_default=sa.text("'CONSULTATION'"))
        batch_op.drop_index(batch_op.f('idx_agenda_prof_date'))
        batch_op.drop_constraint(batch_op.f('fk_agenda_unit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_agenda_prof'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'units', ['unit_id'], ['id'])

    with op.batch_alter_table('appointment_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointment_history_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'appointments', ['appointment_id'], ['id'])

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('duration_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW'),
               nullable=False)
        batch_op.create_foreign_key(None, 'agenda_blocks', ['agenda_block_id'], ['id'])

    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.alter_column('professional_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('note_type',
               existing_type=mysql.ENUM('EVOLUTION', 'NURSING_NOTE', 'INTERCONSULTATION', 'OTHER'),
               nullable=False,
               existing_server_default=sa.text("'EVOLUTION'"))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('version',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_note_prof'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_note_episode'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'episodes', ['episode_id'], ['id'])
        batch_op.create_foreign_key(None, 'professionals', ['professional_id'], ['id'])
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.alter_column('process_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('method',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('file_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['id'])

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_episode'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'episodes', ['episode_id'], ['id'])

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('CONSULTATION', 'EMERGENCY', 'ADMISSION', 'PROCEDURE'),
               nullable=False,
               existing_server_default=sa.text("'CONSULTATION'"))
        batch_op.drop_index(batch_op.f('idx_episodes_person'))
        batch_op.drop_constraint(batch_op.f('fk_episode_person'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_episode_unit'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_episode_prof'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['id'])

    with op.batch_alter_table('insurers', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.alter_column('prestation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('unit_price',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.drop_index(batch_op.f('idx_invoice_items_invoice'))
        batch_op.drop_constraint(batch_op.f('fk_item_prestation'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_item_invoice'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('currency',
               existing_type=mysql.CHAR(length=3),
               type_=sa.String(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.drop_constraint(batch_op.f('fk_invoice_patient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_invoice_episode'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'insurers', ['insurer_id'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['patient_id'], ['id'])
        batch_op.drop_column('episode_id')
        batch_op.drop_column('type')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('emergency_contact',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=140),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('CONSULTATION', 'OPERATING_ROOM', 'LABORATORY', 'IMAGING', 'OTHER'),
               type_=sa.String(length=60),
               nullable=False,
               existing_server_default=sa.text("'CONSULTATION'"))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_column('address')

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_ur_role'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ur_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.drop_constraint(batch_op.f('fk_user_person'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_person'), 'people', ['person_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ur_user'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_ur_role'), 'roles', ['role_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('type',
               existing_type=sa.String(length=60),
               type_=mysql.ENUM('CONSULTATION', 'OPERATING_ROOM', 'LABORATORY', 'IMAGING', 'OTHER'),
               nullable=True,
               existing_server_default=sa.text("'CONSULTATION'"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=140),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('emergency_contact',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.ENUM('CONSULTATION', 'PROCEDURE', 'FEES', 'INSTITUTIONAL', 'OTHER'), server_default=sa.text("'CONSULTATION'"), nullable=True))
        batch_op.add_column(sa.Column('episode_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invoice_episode'), 'episodes', ['episode_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_invoice_patient'), 'people', ['patient_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('total',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('currency',
               existing_type=sa.String(length=3),
               type_=mysql.CHAR(length=3),
               existing_nullable=False,
               existing_server_default=sa.text("'USD'"))
        batch_op.alter_column('patient_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_item_invoice'), 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_item_prestation'), 'prestations', ['prestation_id'], ['id'])
        batch_op.create_index(batch_op.f('idx_invoice_items_invoice'), ['invoice_id'], unique=False)
        batch_op.alter_column('unit_price',
               existing_type=mysql.DECIMAL(precision=12, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('prestation_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('insurers', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=mysql.BIGINT(display_width=20, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('episodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_episode_prof'), 'professionals', ['professional_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_episode_unit'), 'units', ['unit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_episode_person'), 'people', ['person_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_episodes_person'), ['person_id'], unique=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('CONSULTATION', 'EMERGENCY', 'ADMISSION', 'PROCEDURE'),
               nullable=True,
               existing_server_default=sa.text("'CONSULTATION'"))

    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_episode'), 'episodes', ['episode_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('file_id',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('process_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_note_episode'), 'episodes', ['episode_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_note_prof'), 'professionals', ['professional_id'], ['id'], ondelete='SET NULL')
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('version',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('note_type',
               existing_type=mysql.ENUM('EVOLUTION', 'NURSING_NOTE', 'INTERCONSULTATION', 'OTHER'),
               nullable=True,
               existing_server_default=sa.text("'EVOLUTION'"))
        batch_op.alter_column('professional_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'RESCHEDULED', 'NO_SHOW'),
               nullable=True)
        batch_op.alter_column('duration_minutes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('appointment_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_history_ibfk_1'), 'appointments', ['appointment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('agenda_blocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_agenda_prof'), 'professionals', ['professional_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_agenda_unit'), 'units', ['unit_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_agenda_prof_date'), ['professional_id', 'date'], unique=False)
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('CONSULTATION', 'PROCEDURE', 'INTERCONSULTATION'),
               nullable=True,
               existing_server_default=sa.text("'CONSULTATION'"))
        batch_op.alter_column('state',
               existing_type=mysql.ENUM('AVAILABLE', 'BLOCKED', 'OCCUPIED'),
               nullable=True,
               existing_server_default=sa.text("'AVAILABLE'"))

    op.create_table('notification_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('notification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.ENUM('SENT', 'ERROR', 'RETRY'), server_default=sa.text("'SENT'"), nullable=True),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notif_log'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('tax_id', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('contact_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('plan_tariffs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prestation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('valid_from', sa.DATE(), nullable=True),
    sa.Column('valid_to', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_tariff_plan'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prestation_id'], ['prestations.id'], name=op.f('fk_tariff_prestation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('affiliations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('person_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('payer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('plan_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('card_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('valid_from', sa.DATE(), nullable=True),
    sa.Column('valid_to', sa.DATE(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], name=op.f('fk_aff_payer'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], name=op.f('fk_aff_person'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_aff_plan'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('invoice_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', mysql.ENUM('CASH', 'CARD', 'TRANSFER'), server_default=sa.text("'CASH'"), nullable=True),
    sa.Column('reference', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('paid_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_invoice'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_payments_invoice'), ['invoice_id'], unique=False)

    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('key_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('value_text', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('key_name'), ['key_name'], unique=True)

    op.create_table('plans',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('payer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], name=op.f('fk_plan_payer'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prestations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('base_price', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('prestations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('code'), ['code'], unique=True)

    op.create_table('order_items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('prestation_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('instructions', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('PENDING', 'DONE', 'CANCELLED'), server_default=sa.text("'PENDING'"), nullable=True),
    sa.Column('result_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_orderitem_order', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], name='fk_orderitem_result', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('results',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_item_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('result_text', mysql.TEXT(), nullable=True),
    sa.Column('attachments', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_result_order_item'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('access_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('resource', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('details', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_access_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('orders',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('episode_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('professional_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.ENUM('LABORATORY', 'IMAGING', 'PROCEDURE', 'MEDICATION', 'OTHER'), server_default=sa.text("'LABORATORY'"), nullable=True),
    sa.Column('status', mysql.ENUM('ISSUED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'), server_default=sa.text("'ISSUED'"), nullable=True),
    sa.Column('requires_authorization', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], name=op.f('fk_order_episode'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_order_prof'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_orders_episode'), ['episode_id'], unique=False)

    op.create_table('clinical_versions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('entity_type', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('entity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('data_snapshot', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('version', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_rp_perm'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_rp_role'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
